#!/bin/bash

# SSL Setup Script for Canopy Theme Development
# This script sets up SSL certificates for local development

echo "🔐 Setting up SSL certificates for local development..."

# Check if mkcert is installed
if ! command -v mkcert &> /dev/null; then
    echo "❌ mkcert is not installed. Installing via Homebrew..."
    brew install mkcert
fi

# Install local CA
echo "📜 Installing local CA certificate..."
mkcert -install

# Create ssl-certs directory if it doesn't exist
mkdir -p ssl-certs

# Generate certificates
echo "🔑 Generating SSL certificates..."
cd ssl-certs
mkcert getcanopy.local localhost 127.0.0.1 ::1
cd ..

# Get the current directory
CURRENT_DIR=$(pwd)

# Create .env file if it doesn't exist
if [ ! -f .env ]; then
    echo "⚙️  Creating .env file..."
    cat > .env << EOF
# Vite Development Server Configuration
# SSL Configuration for Local Development

# SSL Certificate paths (generated by mkcert)
VITE_DEV_SERVER_KEY=${CURRENT_DIR}/ssl-certs/getcanopy.local+3-key.pem
VITE_DEV_SERVER_CERT=${CURRENT_DIR}/ssl-certs/getcanopy.local+3.pem

# App URL (your Local by Flywheel site URL)
APP_URL=https://getcanopy.local

# Development settings
NODE_ENV=development
VITE_DEV_MODE=true
EOF
    echo "✅ .env file created successfully!"
else
    echo "ℹ️  .env file already exists, skipping creation."
fi

echo ""
echo "🎉 SSL setup complete!"
echo ""
echo "📋 Next steps:"
echo "1. Run 'npm run dev' to start the development server with HTTPS"
echo "2. Visit https://localhost:5173/ to verify SSL is working"
echo "3. Your WordPress site should now load assets over HTTPS"
echo ""
echo "🔧 Troubleshooting:"
echo "- If you see certificate warnings, make sure you ran 'mkcert -install'"
echo "- If certificates expire, re-run this script to generate new ones"
echo "- Certificates are valid for 2+ years from generation date"
